Repository Gmu-Wiki/Gmu-WiKi-Front-V2, pull requests merged in 2023-08, with the labels that each got.

#156 Fix: 최근 수정된 글 404
  src/components/RecentModified/index.jsx
Labels: 🛠️fix

#158 프로모션 페이지 추가
  public/fonts/woff/Pretendard-Black.woff
  public/fonts/woff/Pretendard-Bold.woff
  public/fonts/woff/Pretendard-ExtraBold.woff
  public/fonts/woff/Pretendard-ExtraLight.woff
  public/fonts/woff/Pretendard-Light.woff
  public/fonts/woff/Pretendard-Medium.woff
  public/fonts/woff/Pretendard-Regular.woff
  public/fonts/woff/Pretendard-SemiBold.woff
  public/fonts/woff/Pretendard-Thin.woff
  public/fonts/woff2/Pretendard-Black.woff2
  public/fonts/woff2/Pretendard-Bold.woff2
  public/fonts/woff2/Pretendard-ExtraBold.woff2
  public/fonts/woff2/Pretendard-ExtraLight.woff2
  public/fonts/woff2/Pretendard-Light.woff2
  public/fonts/woff2/Pretendard-Medium.woff2
  public/fonts/woff2/Pretendard-Regular.woff2
  public/fonts/woff2/Pretendard-SemiBold.woff2
  public/fonts/woff2/Pretendard-Thin.woff2
  src/Hooks/useLogin.js
  src/assets/Cloud.jsx
  src/assets/GAuthLogo.jsx
  src/assets/index.jsx
  src/components/Button/style.js
  src/components/GAuthButton.js/index.jsx
  src/components/GAuthButton.js/style.js
  src/components/Header/index.jsx
  src/components/Login/index.jsx
  src/components/Login/style.js
  src/components/Logout/index.jsx
  src/components/PromotionPage/index.jsx
  src/components/PromotionPage/style.js
  src/components/index.js
  src/imgs/PromotionCom.png
  src/imgs/closeToggle.svg
  src/imgs/promotion.png
  src/pages/Main/index.jsx
  src/pages/Promotion/index.jsx
  src/pages/index.js
  src/router/index.jsx
  src/styles/GlobalStyle.jsx
Labels: 📝 should

#159 프로모션 페이지 말풍선 스타일 변경
  src/components/PromotionPage/index.jsx
  src/components/PromotionPage/style.js
Labels: 🛠️fix

#160 최근 수정된 글 width 수정
  public/favicon/favicon.ico
  src/components/RecentModified/style.js
Labels: 🛠️fix

#161 page container 관련 변경 사항
  src/components/BoardDetail/style.js
  src/components/Footer/style.js
  src/components/PageContainer/index.jsx
  src/components/PageContainer/style.js
  src/pages/Club/index.jsx
  src/pages/Event/index.jsx
  src/pages/Inquiry/index.jsx
  src/pages/InquiryDetail/style.js
  src/pages/InquiryWrite/index.jsx
  src/pages/InquiryWrite/style.js
  src/pages/Major/index.jsx
  src/pages/Notice/index.jsx
  src/pages/Role/index.jsx
  src/pages/Schedule/index.jsx
  src/pages/Student/index.jsx
  src/pages/Teacher/index.jsx
Labels: 🛠️fix, 📝 should

#162 footer style 변경
  src/components/Footer/style.js
Labels: 🛠️fix

#167 토글 예시 글자 수정
  src/components/WriteOption/index.jsx
Labels: 📝 should

#166 프로모션 페이지 글자 위치 수정
  src/components/PromotionPage/style.js
Labels: 📝 should

#169 편집, 미리보기 버튼 위치 변경
  src/components/WriteBox/style.js
Labels: 📝 should

#165 페이지 컨테이너 반응형 수정
  src/components/PageContainer/style.js
Labels: 🛠️fix

#171 Fix url에 code가 있던 오류 수정
  src/Hooks/useLogin.js
Labels: 🐛bug, 🏃‍♂️priority

#170 Update recent modified width
  src/components/RecentModified/index.jsx
  src/components/RecentModified/style.js
Labels: 🛠️fix

#176 accessToken 없으면 promotion으로 리다이렉트
  src/components/PromotionPage/style.js
  src/router/index.jsx
Labels: 📝 should

#182 Update History Detail Page
  src/components/HistoryDetailItem/index.jsx
  src/components/HistoryDetailItem/style.js
  src/pages/HistoryDetail/index.jsx
Labels: 🐛bug, 🛠️fix

#188 최근 수정된 글 줄바꿈 이슈 스타일 해결
  src/components/RecentModified/style.js
Labels: 🐛bug, 🛠️fix

#191 생성일자, 수정시각 사이 간격 수정
  src/components/BoardDetail/style.js
  src/components/RecentModified/style.js
Labels: 🛠️fix

#189 메인 페이지 교훈 스타일 수정
  src/pages/Main/style.js
Labels: 🛠️fix

#193 이메일, border 업데이트
  src/pages/Main/index.jsx
  src/pages/Main/style.js
Labels: 🛠️fix

#194 메인페이지 표 반응형 수정
  src/components/Graph/style.js
Labels: 🛠️fix

#195 Update board UI
  src/components/BoardDetail/style.js
  src/components/WriteBox/EditWriteBox/style.js
  src/components/WriteOption/index.jsx
  src/styles/GlobalStyle.jsx
Labels: ⚒️developingping

#196 디테일 (토글) 컴포넌트 스타일 수정
  src/components/Detail/style.js
Labels: 🛠️fix

#197 Remove roleurl In board
  src/Hooks/useBoard.js
  src/Hooks/useContent.js
  src/Hooks/useDelete.js
  src/Hooks/useEdit.js
  src/Hooks/useHistory.js
  src/Hooks/useSearchList.js
  src/Hooks/useUpload.js
  src/components/HistoryItem/index.jsx
  src/components/RecentModified/index.jsx
  src/pages/Club/index.jsx
  src/pages/Event/index.jsx
  src/pages/History/index.jsx
  src/pages/HistoryDetail/index.jsx
  src/pages/Major/index.jsx
  src/pages/Schedule/index.jsx
  src/pages/Student/index.jsx
  src/pages/Teacher/index.jsx
  src/router/index.jsx
Labels: 🛠️fix

#199 Fix board
  src/components/BoardDetail/style.js
  src/components/Header/index.jsx
  src/components/PageContainer/index.jsx
  src/components/WriteBox/EditWriteBox/index.jsx
  src/pages/Club/index.jsx
  src/pages/Major/index.jsx
  src/pages/NotFound/index.jsx
  src/pages/Notice/index.jsx
  src/pages/Schedule/index.jsx
  src/pages/Student/index.jsx
  src/pages/Teacher/index.jsx
Labels: 🛠️fix

#200 Update post url
  src/Hooks/useEdit.js
  src/Hooks/useInquiry.js
  src/Hooks/useMail.js
  src/Hooks/useNotice.js
  src/components/Header/index.jsx
  src/components/PageContainer/index.jsx
  src/components/WriteBox/EditWriteBox/index.jsx
  src/pages/Club/index.jsx
  src/pages/Inquiry/index.jsx
  src/pages/InquiryDetail/index.jsx
  src/pages/Major/index.jsx
  src/pages/NotFound/index.jsx
  src/pages/Notice/index.jsx
  src/pages/Role/index.jsx
  src/pages/Schedule/index.jsx
  src/pages/Student/index.jsx
  src/pages/Teacher/index.jsx
Labels: ⚒️developingping, 🛠️fix

#204 보드 콘텐츠 행간 조정
  src/assets/PromotinCom.jsx
  src/assets/index.jsx
  src/components/BoardDetail/style.js
  src/components/HistoryDetailItem/style.js
  src/components/InquiryDetailItem/style.js
  src/components/NoticeDetail/style.js
  src/components/PromotionPage/index.jsx
  src/components/RecentModified/index.jsx
  src/components/WriteOption/index.jsx
  src/components/WriteOption/style.js
  src/styles/GlobalStyle.jsx
Labels: 🛠️fix, 📝 should

#203 메인페이지 오타, 스타일 수정
  src/components/Detail/style.js
  src/components/Explanation/style.js
  src/components/PageContainer/style.js
  src/components/PromotionPage/style.js
  src/lib/mainPageData.js
  src/pages/Main/index.jsx
  src/pages/Main/style.js
Labels: 🛠️fix

#207 프로모션 이미지 변경
  src/Hooks/useEdit.js
  src/Hooks/useInquiry.js
  src/Hooks/useMail.js
  src/Hooks/useNotice.js
  src/components/BoardDetail/style.js
  src/components/HistoryDetailItem/style.js
  src/components/InquiryDetailItem/style.js
  src/components/NoticeDetail/style.js
  src/components/PromotionPage/index.jsx
  src/components/PromotionPage/style.js
  src/components/RecentModified/index.jsx
  src/components/WriteOption/index.jsx
  src/components/WriteOption/style.js
  src/pages/Inquiry/index.jsx
  src/pages/InquiryDetail/index.jsx
  src/pages/Notice/index.jsx
  src/pages/Role/index.jsx
  src/styles/GlobalStyle.jsx
Labels: 🛠️fix

#208 편집 버튼 미리보기 버튼 스타일 수정
  src/components/WriteBox/index.jsx
  src/components/WriteBox/style.js
  src/components/WriteOption/style.js
Labels: 🏃‍♂️priority, 🛠️fix, 📝 should

#210 글자간 공백 삭제
  src/components/HistoryDetailItem/style.js
Labels: 🐛bug

#211 작성페이지에서 주의 메시지 추가
  src/assets/AlarmIcon.jsx
  src/assets/X.jsx
  src/assets/index.jsx
  src/components/EditNotice/style.js
  src/components/EditWrite/style.js
  src/components/InquiryModal/index.jsx
  src/components/InquiryModal/style.js
  src/components/InquiryWrite/index.jsx
  src/components/InquiryWrite/style.js
  src/components/NoticeWrite/style.js
  src/components/WriteBox/EditWriteBox/index.jsx
  src/components/WriteBox/EditWriteBox/style.js
  src/components/WriteOption/style.js
  src/components/index.js
  src/styles/GlobalStyle.jsx
Labels: 📝 should

#214 모달 완료 로직 수정
  src/components/InquiryModal/index.jsx
  src/components/InquiryWrite/index.jsx
Labels: 📝 should

#218 작성 옵션 툴팁 스타일 수정
  src/components/WriteBox/style.js
  src/components/WriteOption/index.jsx
  src/components/WriteOption/style.js
  src/pages/Main/index.jsx
  src/styles/GlobalStyle.jsx
Labels: 🏃‍♂️priority, 🛠️fix, 📝 should

#219 작성 페이지 새로고침 이벤트 해결, 토글 아래공백 추가
  src/components/EditNotice/index.jsx
  src/components/EditWrite/index.jsx
  src/components/InquiryWrite/index.jsx
  src/components/NoticeWrite/index.jsx
  src/components/WriteBox/index.jsx
  src/components/WriteBox/style.js
  src/styles/GlobalStyle.jsx
Labels: 🏃‍♂️priority, 🛠️fix, 📝 should

#220 작성 페이지 스타일 수정
  src/components/WriteBox/EditWriteBox/style.js
  src/components/WriteBox/style.js
  src/components/WriteOption/style.js
Labels: 🐛bug, 🛠️fix

#222 프로모션 페이지 글자 크기 수정
  src/components/PromotionPage/style.js
Labels: 🛠️fix

#224 img 사이즈 조정
  src/lib/mainPageData.js
  src/styles/GlobalStyle.jsx
Labels: 🛠️fix

#223 사건 2021년도 추가
  src/components/WriteBox/EditWriteBox/index.jsx
  src/pages/Event/index.jsx
Labels: ⚒️developingping, 📝 should

#229 Add Project Page
  src/Hooks/useProject.js
  src/components/Header/dropMenu/index.jsx
  src/components/WriteBox/EditWriteBox/index.jsx
  src/components/index.js
  src/pages/Event/index.jsx
  src/pages/Project/index.jsx
  src/pages/Project/style.js
  src/pages/index.js
  src/router/index.jsx
Labels: ⚒️developingping, 🏃‍♂️priority

#232 Fix Category box
  src/components/WriteBox/EditWriteBox/index.jsx
Labels: 🏃‍♂️priority, 🛠️fix
