Repository Gmu-Wiki/Gmu-WiKi-Front-V2, pull requests merged in 2023-07, with the labels that each got.

#111 내림차순 & 오름차순 + 툴팁 설명추가
  src/Hooks/useEdit.js
  src/Hooks/useFetch.js
  src/Hooks/useInquiry.js
  src/Hooks/useMail.js
  src/Hooks/useUpload.js
  src/apis/index.js
  src/components/InquiryDetailItem/index.jsx
  src/components/WriteOption/index.jsx
  src/components/WriteOption/style.js
  src/pages/Club/index.jsx
  src/pages/Event/index.jsx
  src/pages/Inquiry/index.jsx
  src/pages/Inquiry/style.js
  src/pages/InquiryDetail/index.jsx
  src/pages/Notice/index.jsx
  src/pages/Schedule/index.jsx
  src/pages/Student/index.jsx
  src/pages/Teacher/index.jsx
  src/router/index.jsx
Labels: 🛠️fix

#120 글 삭제
  src/Hooks/useEdit.js
  src/Hooks/useFile.js
  src/Hooks/useInquiry.js
  src/Hooks/useNotice.js
  src/Hooks/useUpload.js
  src/components/HistoryItem/index.jsx
  src/pages/BoardDetail/index.jsx
  src/pages/HistoryDetail/index.jsx
Labels: 🐛bug, 🛠️fix

#128 header 2개인 버그 수정
  src/pages/Edit/index.jsx
  src/pages/EditNotice/index.jsx
Labels: 🐛bug, 🛠️fix

#136 detail한 요소들 수정
  src/Hooks/useFile.js
  src/Hooks/useNotice.js
  src/components/HistoryItem/index.jsx
  src/components/WriteOption/index.jsx
  src/pages/Role/index.jsx
  src/pages/Role/style.js
  src/styles/GlobalStyle.jsx
Labels: 🛠️fix

#133 접었다 펼치는 토글 이미지 보이게 하기
  src/App.js
  src/Hooks/useMarkdown.js
  src/components/BoardDetail/index.jsx
  src/components/WriteBox/EditWriteBox/index.jsx
  src/components/WriteBox/PreviewWriteBox/MarkdownConverter/index.jsx
  src/components/WriteBox/index.jsx
  src/imgs/closeToggle.png
  src/imgs/closeToggle.svg
  src/imgs/openToggle.png
  src/imgs/openToggle.svg
  src/pages/History/index.jsx
  src/styles/GlobalStyle.jsx
  src/styles/style.css
Labels: 🐛bug, 🏃‍♂️priority, 📝 should

#142 change img max-size
  src/styles/GlobalStyle.jsx
Labels: 🐛bug, 🛠️fix

#143 줄 수 바뀌는 로직 각 Write에 적용하기
  src/components/BoardDetail/style.js
  src/components/EditWrite/index.jsx
  src/components/InquiryWrite/index.jsx
  src/components/NoticeWrite/index.jsx
  src/styles/GlobalStyle.jsx
Labels: 🛠️fix, 📝 should

#144 add 글을 등록 할 때 확인 창 추가
  src/App.js
  src/components/EditNotice/index.jsx
  src/components/EditWrite/index.jsx
  src/components/InquiryWrite/index.jsx
  src/components/NoticeWrite/index.jsx
  src/components/WriteBox/index.jsx
  src/styles/GlobalStyle.jsx
  src/styles/style.css
Labels: ⚒️developingping

#149 페이지를 처음 들어갔을 때 404가 뜨는 오류 해결
  package.json
  src/Hooks/index.js
  src/Hooks/useBoard.js
  src/Hooks/useDelete.js
  src/pages/BoardDetail/index.jsx
  src/pages/Student/index.jsx
  src/router/index.jsx
  yarn.lock
Labels: 🛠️fix

#154 edit 커스텀 훅 함수명 변경
  src/Hooks/useEdit.js
Labels: 🐛bug, 🛠️fix

#153 update 문의 작성 후 이동 페이지
  src/Hooks/useInquiry.js
Labels: ⚒️developingping, 🛠️fix
